[webserver]
port = ":8080"


# register data providers
[[providers]]
name = "openindoor"           # provider name is referenced from map layers
type = "postgis"        # the type of data provider currently only supports postgis
host = "$DB_HOST"      #postgis database host
port = $DB_PORT         # postgis database port
database = "$DB_NAME"       # postgis database name
user = "$DB_USER"         # postgis database user
password = "$DB_PASS"           # postgis database password
srid = 4326             # The default srid for this provider. If not provided it will be WebMercator (3857)

  [[providers.layers]]
  name = "building-footprint"
  tablename="building_footprint"
  geometry_fieldname = "geometry"
  srid = 4326
  geometry_type = "Polygon"


  [[providers.layers]]
  name = "building-footprint-centroid"
  tablename="building_footprint"
  geometry_fieldname = "openindoor_centroid"
  srid = 4326
  geometry_type = "Point"
  

[[maps]]
name = "openindoor"
center = [-2.467, 48.264, 7.0]

  [[maps.layers]]
  provider_layer = "openindoor.building-footprint"
  min_zoom = 10
  max_zoom = 20

  [[maps.layers]]
  provider_layer = "openindoor.building-footprint-centroid"
  min_zoom = 0
  max_zoom = 10